server:
  port: 10011
spring:
  application:
    name: leyou-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wangpw2016/leyou-config.git
  rabbitmq:
    host: 127.0.0.1
    username: wangpw
    password: 123456
 #   virtual-host: /leyou


management: #暴露触发消息总线的地址
  endpoints:
    web:
      exposure:
        include: bus-refresh
